# Generated by Django 4.2.5 on 2023-09-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_medibox', '0002_remove_produit_categorie_produit_odronnance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_medibox.produit'),
        ),
    ]
