# Generated by Django 4.2.5 on 2023-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medibox', '0003_alter_commande_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='place',
            field=models.IntegerField(default=1),
        ),
    ]
