# Generated by Django 4.2.3 on 2023-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(max_length=50)),
                ('med1', models.CharField(max_length=50)),
                ('quant1', models.IntegerField(default=1)),
                ('med2', models.CharField(blank=True, max_length=50)),
                ('quant2', models.IntegerField(default=1)),
                ('med3', models.CharField(blank=True, max_length=50)),
                ('quant3', models.IntegerField(default=1)),
                ('med4', models.CharField(blank=True, max_length=50)),
                ('quant4', models.IntegerField(default=1)),
                ('qr_code', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
