# Generated by Django 4.2.3 on 2023-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medecin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cmd',
            field=models.BooleanField(default=False),
        ),
    ]
