# Generated by Django 4.2.5 on 2023-09-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medecin', '0004_prescription_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='maladie',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='med1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
